Repository rune-rs/rune, pull requests merged in 2020-11, with the labels that each got.

#163 Remove unneeded Type and TypeInfo objects
  crates/rune-cli/src/main.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/query/mod.rs
  crates/runestick-macros/src/context.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/context.rs
  crates/runestick/src/hash.rs
  crates/runestick/src/interface.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/macros.rs
  crates/runestick/src/module.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/type_.rs
  crates/runestick/src/type_info.rs
  crates/runestick/src/type_of.rs
  crates/runestick/src/unit.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#164 Make fields for struct meta non-optional
  crates/rune/src/compiling/assemble/expr_object.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/query/mod.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/context.rs
Labels: enhancement

#167 Fix bug with using wrong protocol in Vm for MUL / DIV and add example
  crates/rune/examples/custom_mul.rs
  crates/runestick/src/vm.rs
Labels: bug

#170 Add support for overloading derived field functions
  book/src/field_functions.md
  crates/rune/examples/checked_add_assign.rs
  crates/rune/src/testing.rs
  crates/rune/tests/test_all/external_ops.rs
  crates/runestick-macros/src/context.rs
  crates/runestick-macros/src/internals.rs
  crates/runestick/src/module.rs
  crates/runestick/src/vm_error.rs
Labels: enhancement

#173 Get rid of reverse lookup of items
  crates/rune/src/indexing/index.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/query/query_error.rs
  crates/rune/src/shared/items.rs
Labels: enhancement

#174 Make use of a shared id generator
  crates/rune/src/compiling/mod.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/shared/gen.rs
  crates/rune/src/shared/items.rs
  crates/rune/src/shared/mod.rs
  crates/rune/src/worker/mod.rs
  crates/runestick/src/id.rs
Labels: enhancement

#175 Simplify and fix imports for better visibility checks
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/query/query_error.rs
  crates/rune/tests/test_all/compiler_use.rs
  crates/rune/tests/test_all/compiler_visibility.rs
  crates/runestick/src/compile_meta.rs
Labels: bug, enhancement

#178 Add std::any module and clear up some function type hash confusion
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/testing.rs
  crates/rune/tests/test_all.rs
  crates/rune/tests/test_all/mod.rs
  crates/rune/tests/test_all/type_name_native.rs
  crates/rune/tests/test_all/type_name_rune.rs
  crates/runestick/Cargo.toml
  crates/runestick/src/context.rs
  crates/runestick/src/function.rs
  crates/runestick/src/interface.rs
  crates/runestick/src/modules/any.rs
  crates/runestick/src/modules/mod.rs
  crates/runestick/src/protocol.rs
  crates/runestick/src/runtime_context.rs
  crates/runestick/src/unit.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#180 Initial introduction of range expressions
  assets/tokens.yaml
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/expr_range.rs
  crates/rune/src/ast/expr_return.rs
  crates/rune/src/ast/generated.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/compiling/assemble/expr.rs
  crates/rune/src/compiling/assemble/expr_range.rs
  crates/rune/src/compiling/assemble/mod.rs
  crates/rune/src/compiling/assemble/prelude.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/parsing/lexer.rs
  crates/rune/tests/test_all/mod.rs
  crates/rune/tests/test_all/test_range.rs
  crates/runestick/src/context.rs
  crates/runestick/src/inst.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/mod.rs
  crates/runestick/src/modules/ops.rs
  crates/runestick/src/range.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vm.rs
Labels: enhancement
