Repository rune-rs/rune, pull requests merged in 2020-09, with the labels that each got.

#12 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#40 Support assigning to fields (fixes #38)
  .gitignore
  crates/rune-cli/src/main.rs
  crates/rune-testing/tests/vm_assign_exprs.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/token.rs
  crates/rune/src/compile/expr_binary.rs
  crates/rune/src/error.rs
  crates/rune/src/scopes.rs
Labels: bug

#36 [CI] Cache Cargo build
  .github/workflows/build.yml
Labels: enhancement

#35 Project CleanUp with Clippy
  crates/rune-cli/src/main.rs
  crates/rune-modules/src/process.rs
  crates/rune-testing/src/lib.rs
  crates/rune-testing/tests/vm_general.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/ident.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/label.rs
  crates/rune/src/compiler.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/index.rs
  crates/rune/src/lexer.rs
  crates/rune/src/quote.rs
  crates/rune/src/sources.rs
  crates/rune/src/unit_builder.rs
  crates/rune/src/worker.rs
  crates/runestick/src/any.rs
  crates/runestick/src/context.rs
  crates/runestick/src/generator.rs
  crates/runestick/src/vm.rs
  crates/runestick/src/vm_call.rs
  crates/runestick/src/vm_error.rs
  crates/runestick/src/vm_execution.rs
Labels: clippy

#53 Reduced loop{} overhead
  crates/rune/src/compile/expr_loop.rs
Labels: enhancement

#63 Make the representation of items more compact
  crates/rune-testing/examples/use_references.rs
  crates/rune-testing/src/lib.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/index.rs
  crates/rune/src/items.rs
  crates/rune/src/unit_builder.rs
  crates/rune/src/worker.rs
  crates/runestick/Cargo.toml
  crates/runestick/src/context.rs
  crates/runestick/src/hash.rs
  crates/runestick/src/item.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/module.rs
  crates/runestick/src/names.rs
Labels: enhancement

#68 Fix releases build
  Cargo.toml
  README.md
  book/src/async.md
  book/src/call_frames.md
  book/src/closures.md
  book/src/compiler_guide.md
  book/src/control_flow.md
  book/src/dynamic_types.md
  book/src/enums.md
  book/src/functions.md
  book/src/generators.md
  book/src/getting_started.md
  book/src/instance_functions.md
  book/src/items_imports.md
  book/src/loops.md
  book/src/macros.md
  book/src/objects.md
  book/src/pattern_matching.md
  book/src/primitives.md
  book/src/streams.md
  book/src/structs.md
  book/src/template_strings.md
  book/src/the_stack.md
  book/src/try_operator.md
  book/src/tuples.md
  book/src/types.md
  book/src/variables.md
  book/src/vectors.md
  crates/rune-cli/README.md
  crates/rune-cli/src/main.rs
  crates/rune-languageserver/src/main.rs
  crates/rune/README.md
  crates/rune/src/lib.rs
  tools/builder/Cargo.toml
  tools/builder/README.md
  tools/builder/src/main.rs
Labels: build

#69 vscode: add preliminary support for downloading languageserver binaries
  .vscode/launch.json
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/src/main.ts
  editors/code/src/net.ts
  editors/code/src/persistent_state.ts
  editors/code/src/util.ts
Labels: changelog, enhancement, languageserver

#74 languageserver: Make use of build sources instead of awkward mapping
  .vscode/launch.json
  crates/rune-languageserver/src/state.rs
  crates/rune/src/compile/expr_async.rs
  crates/rune/src/compile/expr_binary.rs
  crates/rune/src/compile/expr_call.rs
  crates/rune/src/compile/expr_closure.rs
  crates/rune/src/compile/expr_field_access.rs
  crates/rune/src/compile/expr_path.rs
  crates/rune/src/compile/expr_self.rs
  crates/rune/src/compile/lit_object.rs
  crates/rune/src/compile_error.rs
  crates/rune/src/compile_visitor.rs
  crates/rune/src/compiler.rs
  crates/rune/src/index.rs
  crates/rune/src/lib.rs
  crates/rune/src/query.rs
  crates/rune/src/scopes.rs
  crates/rune/src/source_loader.rs
  crates/rune/src/sources.rs
  crates/rune/src/worker.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/context.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/source.rs
Labels: bug, languageserver

#77 Add support for a wasm-based Rune Playground
  .github/workflows/site.yml
  Cargo.toml
  crates/rune-languageserver/src/state.rs
  crates/rune-wasm/.gitignore
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/package-lock.json
  crates/rune-wasm/package.json
  crates/rune-wasm/rollup.config.js
  crates/rune-wasm/rune.js
  crates/rune-wasm/src/lib.rs
  crates/rune/src/compile_error.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/errors.rs
  crates/rune/src/index.rs
  crates/rune/src/load_error.rs
  crates/rune/src/query.rs
  crates/rune/src/source_loader.rs
  crates/rune/src/warning.rs
  crates/rune/src/worker.rs
  crates/runestick/Cargo.toml
  crates/runestick/src/access.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/source.rs
  crates/runestick/src/vm_error.rs
  site/.gitignore
  site/content/play.md
  site/sass/_colors.scss
  site/sass/style.scss
  site/templates/base.html
  site/templates/macros.html
  site/templates/play.html
Labels: enhancement, site

#80 Limit execution and support output in Playground
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/src/lib.rs
  crates/runestick/src/budget.rs
  crates/runestick/src/context.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/core.rs
  crates/runestick/src/stack.rs
  crates/runestick/src/vm.rs
  crates/runestick/src/vm_execution.rs
  site/templates/play.html
Labels: enhancement, site

#82 Make rune snippets work everywhere
  crates/rune-wasm/rollup.config.js
  site/.gitignore
  site/config.toml
  site/content/posts/2020-09-18-hello-internet.md
  site/sass/style.scss
  site/static/index.js
  site/templates/base.html
  site/templates/play.html
  site/templates/shortcodes/rune.html
Labels: enhancement, site

#84 fix some broken links to the book in the README
  README.md
Labels: bug, documentation

#86 Fix more broken links (relates #84)
  README.md
  crates/rune-cli/README.md
  crates/rune-cli/src/main.rs
  crates/rune-languageserver/README.md
  crates/rune-languageserver/src/lib.rs
  crates/rune-languageserver/src/main.rs
  crates/rune-macros/README.md
  crates/rune-macros/src/lib.rs
  crates/rune-modules/README.md
  crates/rune-modules/src/lib.rs
  crates/rune/README.md
  crates/rune/src/lib.rs
  crates/runestick-macros/README.md
  crates/runestick-macros/src/lib.rs
  crates/runestick/README.md
  crates/runestick/src/lib.rs
  editors/code/README.md
Labels: bug, documentation

#89 Hook up a few browser functions to showcase async functionality in rune-wasm
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/module.js
  crates/rune-wasm/src/core.rs
  crates/rune-wasm/src/http.rs
  crates/rune-wasm/src/lib.rs
  crates/rune-wasm/src/time.rs
  site/README.md
  site/content/_index.md
  site/sass/style.scss
  site/static/index.js
  site/templates/play.html
  site/templates/shortcodes/rune.html
Labels: enhancement, site

#95 Add tokio_async_call example and make sure Unit and Context are thread-safe
  crates/rune/Cargo.toml
  crates/rune/examples/tokio_async_call.rs
  crates/rune/src/eval/expr.rs
  crates/rune/src/eval/expr_if.rs
  crates/rune/src/testing.rs
  crates/runestick/src/context.rs
  crates/runestick/src/unit.rs
Labels: enhancement

#98 Parse both attributes and visibility externally from Item
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/file.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_impl.rs
  crates/rune/src/ast/item_mod.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/item_use.rs
  crates/rune/src/ast/vis.rs
  crates/rune/src/parse_error.rs
  crates/rune/src/traits.rs
Labels: bug, parser

#99 Replace ConstCompiler with a more generic IR and IrInterpreter
  Cargo.toml
  crates/rune-ir/Cargo.toml
  crates/rune-ir/src/lib.rs
  crates/rune/Cargo.toml
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/compile/const_value.rs
  crates/rune/src/compiler.rs
  crates/rune/src/eval/block.rs
  crates/rune/src/eval/condition.rs
  crates/rune/src/eval/expr.rs
  crates/rune/src/eval/expr_binary.rs
  crates/rune/src/eval/expr_block.rs
  crates/rune/src/eval/expr_break.rs
  crates/rune/src/eval/expr_if.rs
  crates/rune/src/eval/expr_let.rs
  crates/rune/src/eval/expr_lit.rs
  crates/rune/src/eval/expr_loop.rs
  crates/rune/src/eval/expr_while.rs
  crates/rune/src/eval/ir.rs
  crates/rune/src/eval/ir_binary.rs
  crates/rune/src/eval/ir_branches.rs
  crates/rune/src/eval/ir_break.rs
  crates/rune/src/eval/ir_decl.rs
  crates/rune/src/eval/ir_loop.rs
  crates/rune/src/eval/ir_scope.rs
  crates/rune/src/eval/ir_set.rs
  crates/rune/src/eval/ir_template.rs
  crates/rune/src/eval/ir_tuple.rs
  crates/rune/src/eval/ir_vec.rs
  crates/rune/src/eval/lit_tuple.rs
  crates/rune/src/eval/lit_vec.rs
  crates/rune/src/eval/mod.rs
  crates/rune/src/eval/prelude.rs
  crates/rune/src/ir_compiler.rs
  crates/rune/src/ir_interpreter.rs
  crates/rune/src/lib.rs
  crates/rune/src/query.rs
  crates/rune/src/warning.rs
  crates/rune/src/worker.rs
  crates/runestick/src/const_value.rs
Labels: compiler, enhancement

#102 Enable rand again
  crates/rune-modules/Cargo.toml
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/src/lib.rs
  crates/rune/Cargo.toml
  crates/rune/src/lib.rs
  scripts/rand.rn
Labels: bug

#103 Move rune-ir into rune crate
  Cargo.toml
  crates/rune-ir/Cargo.toml
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/internals.rs
  crates/rune-macros/src/parse.rs
  crates/rune-macros/src/spanned.rs
  crates/rune-macros/src/to_tokens.rs
  crates/rune/Cargo.toml
  crates/rune/src/eval/prelude.rs
  crates/rune/src/ir.rs
  crates/rune/src/ir_compiler.rs
  crates/rune/src/ir_interpreter.rs
  crates/rune/src/lib.rs
  crates/rune/src/query.rs
Labels: enhancement

#104 Add complete support for constant dynamic collections
  crates/rune/src/compile/const_value.rs
  crates/rune/src/eval/ir.rs
  crates/rune/src/eval/ir_object.rs
  crates/rune/src/eval/mod.rs
  crates/rune/src/eval/prelude.rs
  crates/rune/src/ir.rs
  crates/rune/src/ir_compiler.rs
  crates/rune/src/tests/vm_const_exprs.rs
  crates/rune/src/unit_builder.rs
  crates/runestick/src/const_value.rs
  crates/runestick/src/from_value.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/vec.rs
  crates/runestick/src/named.rs
  crates/runestick/src/object.rs
  crates/runestick/src/serde.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/to_value.rs
  crates/runestick/src/tuple.rs
  crates/runestick/src/unit.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vec.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#105 Support more forms of assignment in constant expressions
  crates/rune/src/compile/const_value.rs
  crates/rune/src/compile_error.rs
  crates/rune/src/eval/ir.rs
  crates/rune/src/eval/ir_object.rs
  crates/rune/src/eval/ir_scope.rs
  crates/rune/src/eval/ir_set.rs
  crates/rune/src/eval/ir_template.rs
  crates/rune/src/eval/ir_vec.rs
  crates/rune/src/eval/mod.rs
  crates/rune/src/eval/prelude.rs
  crates/rune/src/ir.rs
  crates/rune/src/ir_compiler.rs
  crates/rune/src/ir_interpreter.rs
  crates/runestick/src/const_value.rs
  crates/runestick/src/lib.rs
Labels: enhancement

#108 Introduce IrError as its own interpreter error
  crates/rune-languageserver/src/state.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/src/compile_error.rs
  crates/rune/src/compiler.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/eval/ir.rs
  crates/rune/src/eval/ir_assign.rs
  crates/rune/src/eval/ir_binary.rs
  crates/rune/src/eval/ir_loop.rs
  crates/rune/src/eval/ir_template.rs
  crates/rune/src/eval/mod.rs
  crates/rune/src/eval/prelude.rs
  crates/rune/src/ir.rs
  crates/rune/src/ir_compiler.rs
  crates/rune/src/ir_error.rs
  crates/rune/src/ir_interpreter.rs
  crates/rune/src/ir_value.rs
  crates/rune/src/lib.rs
  crates/rune/src/load_error.rs
  crates/rune/src/query.rs
  crates/rune/src/scopes.rs
Labels: enhancement

#111 Remove a couple of parsers in favor of generic grouped
  crates/rune-macros/src/spanned.rs
  crates/rune-macros/src/to_tokens.rs
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/expr_block.rs
  crates/rune/src/ast/expr_is.rs
  crates/rune/src/ast/expr_is_not.rs
  crates/rune/src/ast/expr_lit.rs
  crates/rune/src/ast/expr_match.rs
  crates/rune/src/ast/expr_select.rs
  crates/rune/src/ast/grouped.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/lit.rs
  crates/rune/src/ast/lit_object.rs
  crates/rune/src/ast/lit_tuple.rs
  crates/rune/src/ast/lit_vec.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/ast/parenthesized.rs
  crates/rune/src/compiling/compile/expr_call.rs
  crates/rune/src/compiling/compile/expr_select.rs
  crates/rune/src/compiling/compile/item_fn.rs
  crates/rune/src/compiling/compile/lit_object.rs
  crates/rune/src/compiling/compile/lit_tuple.rs
  crates/rune/src/compiling/compile/lit_vec.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/query.rs
Labels: enhancement

#112 Add runtime support for unit structs and variants
  crates/rune-languageserver/src/state.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/compiling/compile/expr_call.rs
  crates/rune/src/compiling/compile/lit_object.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/query.rs
  crates/rune/src/tests/vm_function.rs
  crates/runestick-macros/src/context.rs
  crates/runestick-macros/src/from_value.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/context.rs
  crates/runestick/src/debug.rs
  crates/runestick/src/function.rs
  crates/runestick/src/inst.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/core.rs
  crates/runestick/src/serde.rs
  crates/runestick/src/unit.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#113 Add support for enums to derive FromValue
  crates/rune/src/compiling/compile/lit_object.rs
  crates/rune/src/tests/vm_test_from_value_derive.rs
  crates/runestick-macros/src/context.rs
  crates/runestick-macros/src/from_value.rs
  crates/runestick-macros/tests/test_macro.rs
  crates/runestick/src/inst.rs
  crates/runestick/src/item.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/core.rs
  crates/runestick/src/serde.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vm.rs
  crates/runestick/src/vm_error.rs
Labels: enhancement

#114 Expand macros earlier so they include constants
  crates/rune-modules/README.md
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_async.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/expr_block.rs
  crates/rune/src/ast/expr_group.rs
  crates/rune/src/ast/expr_if.rs
  crates/rune/src/ast/expr_is.rs
  crates/rune/src/ast/expr_is_not.rs
  crates/rune/src/ast/expr_match.rs
  crates/rune/src/ast/expr_unary.rs
  crates/rune/src/ast/file.rs
  crates/rune/src/ast/grouped.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/item_use.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/ast/stmt.rs
  crates/rune/src/compiling/compile/expr.rs
  crates/rune/src/compiling/compile/prelude.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/index_scopes.rs
  crates/rune/src/load/sources.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/parsing/parse_error.rs
  crates/rune/src/query.rs
  crates/rune/src/shared/items.rs
  crates/rune/src/spanned.rs
  crates/rune/src/worker.rs
  crates/runestick/src/item.rs
Labels: enhancement

#117 Fix issue with constant expression
  crates/rune/src/ir/eval/ir_scope.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/ir/ir_interpreter.rs
  crates/rune/src/shared/scopes.rs
  crates/rune/src/tests/vm_const_exprs.rs
Labels: bug

#118 Introduce opaque identifiers for indexed items
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/internals.rs
  crates/rune-macros/src/parse.rs
  crates/rune-macros/src/to_tokens.rs
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr_closure.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/lit_template.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/compiling/compile/block.rs
  crates/rune/src/compiling/compile/expr_block.rs
  crates/rune/src/compiling/compile/expr_call.rs
  crates/rune/src/compiling/compile/expr_closure.rs
  crates/rune/src/compiling/compile/expr_path.rs
  crates/rune/src/compiling/compile/expr_select.rs
  crates/rune/src/compiling/compile/lit_object.rs
  crates/rune/src/compiling/compile/lit_template.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/lib.rs
  crates/rune/src/parsing/id.rs
  crates/rune/src/parsing/mod.rs
  crates/rune/src/parsing/opaque.rs
  crates/rune/src/query.rs
  crates/rune/src/spanned.rs
Labels: enhancement

#120 Stop keeping track of end span
  crates/rune/src/ast/attribute.rs
  crates/rune/src/ast/macro_call.rs
  crates/rune/src/ast/token.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/macros/token_stream.rs
  crates/rune/src/parsing/lexer.rs
  crates/rune/src/parsing/parser.rs
  crates/rune/src/spanned.rs
  crates/runestick/src/span.rs
Labels: enhancement

#121 Defer parsing of items and expressions to their enum implementation
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_assign.rs
  crates/rune/src/ast/expr_await.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/expr_block.rs
  crates/rune/src/ast/expr_break.rs
  crates/rune/src/ast/expr_call.rs
  crates/rune/src/ast/expr_closure.rs
  crates/rune/src/ast/expr_field_access.rs
  crates/rune/src/ast/expr_for.rs
  crates/rune/src/ast/expr_group.rs
  crates/rune/src/ast/expr_if.rs
  crates/rune/src/ast/expr_index.rs
  crates/rune/src/ast/expr_is.rs
  crates/rune/src/ast/expr_is_not.rs
  crates/rune/src/ast/expr_let.rs
  crates/rune/src/ast/expr_lit.rs
  crates/rune/src/ast/expr_loop.rs
  crates/rune/src/ast/expr_match.rs
  crates/rune/src/ast/expr_return.rs
  crates/rune/src/ast/expr_select.rs
  crates/rune/src/ast/expr_try.rs
  crates/rune/src/ast/expr_unary.rs
  crates/rune/src/ast/expr_while.rs
  crates/rune/src/ast/expr_yield.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_impl.rs
  crates/rune/src/ast/item_mod.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/item_use.rs
  crates/rune/src/ast/local.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/ast/stmt.rs
  crates/rune/src/compiling/compile/block.rs
  crates/rune/src/compiling/compile/expr.rs
  crates/rune/src/compiling/compile/local.rs
  crates/rune/src/compiling/compile/mod.rs
  crates/rune/src/compiling/compile/prelude.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/spanned.rs
  crates/rune/src/tests/compiler_attributes.rs
  crates/rune/src/tests/compiler_warnings.rs
Labels: enhancement, parser

#122 Support defining and calling constant functions
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_call.rs
  crates/rune/src/ast/grouped.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/compiling/compile/expr_call.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/compiling/scopes.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/index_scopes.rs
  crates/rune/src/indexing/mod.rs
  crates/rune/src/ir/ir.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/ir/ir_interpreter.rs
  crates/rune/src/parsing/mod.rs
  crates/rune/src/parsing/opaque.rs
  crates/rune/src/parsing/parse_error.rs
  crates/rune/src/query.rs
  crates/rune/src/spanned.rs
  crates/rune/src/tests/compiler_attributes.rs
  crates/rune/src/tests/compiler_fn.rs
  crates/rune/src/tests/compiler_general.rs
  crates/rune/src/tests/compiler_paths.rs
  crates/rune/src/tests/mod.rs
  crates/rune/src/tests/vm_const_exprs.rs
  crates/runestick/src/compile_meta.rs
  crates/runestick/src/id.rs
  crates/runestick/src/lib.rs
Labels: enhancement

#123 More constant expressions
  crates/rune/src/ir/ir_error.rs
  crates/rune/src/ir/ir_interpreter.rs
  crates/rune/src/shared/scopes.rs
  crates/rune/src/tests/vm_const_exprs.rs
Labels: enhancement

#126 Site updates
  crates/rune-cli/src/main.rs
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/src/lib.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/lib.rs
  site/content/posts/2020-10-01-tmir1.md
  site/sass/_menu.scss
  site/sass/style.scss
  site/static/index.js
  site/templates/play.html
  site/templates/shortcodes/rune.html
Labels: site

#129 Improve diagnostics on imports and add tests
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/tests/compiler_paths.rs
  crates/rune/src/worker.rs
  crates/runestick/src/item.rs
Labels: enhancement
