Repository rune-rs/rune, pull requests merged in 2020-12, with the labels that each got.

#183 Support continue in loops
  assets/tokens.yaml
  crates/rune-macros/src/quote/generated.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_continue.rs
  crates/rune/src/ast/generated.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/compiling/assemble/expr.rs
  crates/rune/src/compiling/assemble/expr_break.rs
  crates/rune/src/compiling/assemble/expr_continue.rs
  crates/rune/src/compiling/assemble/expr_for.rs
  crates/rune/src/compiling/assemble/expr_loop.rs
  crates/rune/src/compiling/assemble/expr_while.rs
  crates/rune/src/compiling/assemble/mod.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/loops.rs
  crates/rune/src/indexing/index.rs
  crates/rune/tests/test_all/mod.rs
  crates/rune/tests/test_all/test_continue.rs
Labels: enhancement

#185 expand on Result, Option, Iterator
  crates/rune/tests/test_all/mod.rs
  crates/rune/tests/test_all/test_iter.rs
  crates/rune/tests/test_all/test_option.rs
  crates/rune/tests/test_all/test_result.rs
  crates/runestick/src/iterator.rs
  crates/runestick/src/modules/iter.rs
  crates/runestick/src/modules/option.rs
  crates/runestick/src/modules/result.rs
Labels: enhancement

#184 Fix negative fractional literals
  crates/rune/src/compiling/assemble/expr_unary.rs
  crates/rune/src/parsing/lexer.rs
  crates/rune/tests/test_all/vm_literals.rs
Labels: bug

#187 AoC Day 2 improvements
  crates/rune-cli/src/main.rs
  crates/runestick/src/context.rs
  crates/runestick/src/iterator.rs
  crates/runestick/src/modules/char.rs
  crates/runestick/src/modules/iter.rs
  crates/runestick/src/modules/mod.rs
  crates/runestick/src/modules/string.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#190 Make it easier to profile Vm
  benches/Cargo.toml
  crates/runestick/Cargo.toml
  crates/runestick/src/budget.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#191 Improve runtime hashing performance
  crates/runestick/src/hash.rs
  crates/runestick/src/module.rs
Labels: performance

#193 Add fibonacci and brainfuck interpreter benchmarks
  benches/benches/aoc_2020_1b.rs
  benches/benches/brainfuck.rs
  benches/benches/fib.rs
  crates/runestick/src/modules/char.rs
  crates/runestick/src/modules/vec.rs
  crates/runestick/src/vec.rs
  crates/runestick/src/vm_error.rs
  tests/Cargo.toml
  tests/src/capture_output.rs
  tests/src/lib.rs
Labels: performance

#198 Fix broken WASM dep with parking_lot_core 0.8.1
  crates/rune-cli/Cargo.toml
  crates/rune-languageserver/Cargo.toml
  crates/rune-languageserver/src/lib.rs
  crates/rune-languageserver/src/state.rs
  crates/rune-macros/Cargo.toml
  crates/rune-modules/Cargo.toml
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/package-lock.json
  crates/rune-wasm/package.json
  crates/rune/Cargo.toml
  crates/rune/src/diagnostics.rs
  crates/runestick-macros/Cargo.toml
  crates/runestick/Cargo.toml
  examples/Cargo.toml
  tests/Cargo.toml
Labels: bug

#199 add set difference, intersection, union, fix sum error op
  crates/runestick/src/iterator.rs
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/type_of.rs
Labels: enhancement

#201 Make HashMap INDEX_GET op fallible and fix Vm bug with invoking it
  crates/runestick/src/key.rs
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/vm.rs
  crates/runestick/src/vm_error.rs
Labels: bug

#204 AoC Day 6 additions
  crates/runestick/src/modules/collections.rs
Labels: enhancement

#205 AoC day 7 changes
  crates/runestick/src/modules/result.rs
Labels: enhancement

#206 Add parsing for path segment generics
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/expr_field_access.rs
  crates/rune/src/ast/grouped.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/compiling/assemble/const_value.rs
  crates/rune/src/compiling/assemble/expr_assign.rs
  crates/rune/src/compiling/assemble/expr_binary.rs
  crates/rune/src/compiling/assemble/expr_call.rs
  crates/rune/src/compiling/assemble/expr_field_access.rs
  crates/rune/src/compiling/assemble/expr_object.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/compiling/compiler.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/worker/import.rs
Labels: enhancement

#209 Expose APIs to conditionally construct Interface instances
  crates/runestick/src/interface.rs
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/object.rs
  crates/runestick/src/protocol.rs
  crates/runestick/src/range.rs
  crates/runestick/src/tuple.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vec.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#210 Rework how protocol functions are called
  crates/runestick/src/env.rs
  crates/runestick/src/format.rs
  crates/runestick/src/function.rs
  crates/runestick/src/guarded_args.rs
  crates/runestick/src/interface.rs
  crates/runestick/src/internal.rs
  crates/runestick/src/iterator.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/any.rs
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/protocol_caller.rs
  crates/runestick/src/shared.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/value.rs
  crates/runestick/src/vec.rs
  crates/runestick/src/vm.rs
Labels: enhancement

#211 Add {Ref, Mut}::{map, try_map} for projecting owned references
  crates/runestick/src/access.rs
  crates/runestick/src/shared.rs
Labels: enhancement

#215 Treat variants separately to fix their value_ptr_eq impl
  crates/runestick-macros/src/context.rs
  crates/runestick-macros/src/from_value.rs
  crates/runestick/src/function.rs
  crates/runestick/src/lib.rs
  crates/runestick/src/modules/core.rs
  crates/runestick/src/static_type.rs
  crates/runestick/src/value.rs
  crates/runestick/src/variant.rs
  crates/runestick/src/vm.rs
  tests/tests/variants.rs
  tests/tests/vm_function.rs
Labels: bug

#216 Day 8 changes
  crates/runestick/src/key.rs
  crates/runestick/src/modules/vec.rs
  crates/runestick/src/value.rs
  crates/runestick/src/variant.rs
Labels: enhancement

#222 Deny #[test] fns declared in nested items
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/attrs/attributes.rs
  crates/rune/src/compiling/compile_error.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/worker/mod.rs
  tests/tests/test_attribute.rs
Labels: enhancement

#227 Move all diagnostics into one type
  crates/rune-cli/src/main.rs
  crates/rune-languageserver/src/state.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/compiling/v1/assemble/builtin_template.rs
  crates/rune/src/compiling/v1/assemble/const_value.rs
  crates/rune/src/compiling/v1/assemble/expr_call.rs
  crates/rune/src/compiling/v1/assemble/expr_closure.rs
  crates/rune/src/compiling/v1/assemble/expr_field_access.rs
  crates/rune/src/compiling/v1/assemble/expr_let.rs
  crates/rune/src/compiling/v1/assemble/expr_object.rs
  crates/rune/src/compiling/v1/assemble/expr_tuple.rs
  crates/rune/src/compiling/v1/assemble/expr_vec.rs
  crates/rune/src/compiling/v1/assemble/lit_bool.rs
  crates/rune/src/compiling/v1/assemble/lit_byte.rs
  crates/rune/src/compiling/v1/assemble/lit_byte_str.rs
  crates/rune/src/compiling/v1/assemble/lit_char.rs
  crates/rune/src/compiling/v1/assemble/lit_number.rs
  crates/rune/src/compiling/v1/assemble/lit_str.rs
  crates/rune/src/compiling/v1/assemble/local.rs
  crates/rune/src/compiling/v1/mod.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/lib.rs
  crates/rune/src/load/diagnostics.rs
  crates/rune/src/load/errors.rs
  crates/rune/src/load/mod.rs
  crates/rune/src/worker/mod.rs
  examples/examples/basic_add.rs
  examples/examples/custom_instance_fn.rs
  examples/examples/custom_mul.rs
  examples/examples/run_diagnostics.rs
  examples/examples/run_minimal.rs
  examples/examples/use_references.rs
  examples/examples/vec_args.rs
  tests/src/lib.rs
  tests/tests/external_ops.rs
  tests/tests/getter_setter.rs
  tests/tests/reference_error.rs
Labels: enhancement

#228 Unified diagnostics
  crates/rune-cli/src/main.rs
  crates/rune-languageserver/src/state.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/lib.rs
  crates/rune/src/load/diagnostics.rs
  crates/rune/src/load/error.rs
  crates/rune/src/load/mod.rs
  crates/rune/src/load/warning.rs
  crates/rune/src/worker/mod.rs
  tests/src/lib.rs
  tests/tests/compiler_paths.rs
Labels: enhancement

#229 add {HashMap, HashSet}::clone, {HashMap, HashSet, Vec}::remove
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/modules/vec.rs
  crates/runestick/src/vec.rs
Labels: enhancement, rust-likeness

#230 fix chained else-ifs
  crates/rune/src/compiling/v1/assemble/expr_if.rs
Labels: bug

#233 add Vec::sort_by and String::cmp
  crates/runestick/src/any.rs
  crates/runestick/src/context.rs
  crates/runestick/src/modules/cmp.rs
  crates/runestick/src/modules/mod.rs
  crates/runestick/src/modules/string.rs
  crates/runestick/src/modules/vec.rs
Labels: rust-likeness
