Repository rune-rs/rune, pull requests merged in 2021-11, with the labels that each got.

#295 Don't require macro function to be Copy
  crates/runestick/src/module.rs
Labels: enhancement

#301 Reduce memory footprint of debug info and future proof its API
  crates/rune-languageserver/src/state.rs
  crates/rune/src/compiling/assembly.rs
  crates/rune/src/compiling/mod.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/runestick/src/debug.rs
  crates/runestick/src/label.rs
  crates/runestick/src/source.rs
Labels: enhancement

#305 More String to Box<str>
  crates/runestick-macros/src/context.rs
  crates/runestick/src/context.rs
  crates/runestick/src/item.rs
  crates/runestick/src/module.rs
  crates/runestick/src/named.rs
  crates/runestick/src/protocol.rs
Labels: enhancement

#310 Refactor build entrypoint and add sources! macro
  README.md
  crates/rune-cli/src/main.rs
  crates/rune-languageserver/src/state.rs
  crates/rune-macros/src/lib.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/README.md
  crates/rune/src/build.rs
  crates/rune/src/compile/mod.rs
  crates/rune/src/lib.rs
  crates/rune/src/runtime/from_value.rs
  crates/rune/src/runtime/runtime_context.rs
  crates/rune/src/runtime/to_value.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/sources.rs
  examples/examples/checked_add_assign.rs
  examples/examples/custom_instance_fn.rs
  examples/examples/custom_mul.rs
  examples/examples/minimal.rs
  examples/examples/native_function.rs
  examples/examples/object.rs
  examples/examples/parsing_in_macro.rs
  examples/examples/proxy.rs
  examples/examples/references.rs
  examples/examples/rune_function.rs
  examples/examples/tokio_spawn.rs
  examples/examples/tuple.rs
  examples/examples/vec_args.rs
  examples/examples/vec_tuple.rs
  examples/examples/vector.rs
  tests/src/lib.rs
  tests/tests/custom_macros.rs
  tests/tests/external_ops.rs
  tests/tests/getter_setter.rs
  tests/tests/reference_error.rs
Labels: enhancement

#311 Remove the need for two lifetimes when referencing the Query engine
  crates/rune-modules/src/core.rs
  crates/rune-modules/src/experiments/mod.rs
  crates/rune-modules/src/experiments/stringy_math_macro.rs
  crates/rune-modules/src/fmt.rs
  crates/rune-modules/src/io.rs
  crates/rune-modules/src/macros.rs
  crates/rune-modules/src/test.rs
  crates/rune/src/ast/ident.rs
  crates/rune/src/ast/label.rs
  crates/rune/src/ast/lit.rs
  crates/rune/src/ast/lit_char.rs
  crates/rune/src/ast/token.rs
  crates/rune/src/compile/mod.rs
  crates/rune/src/compile/module.rs
  crates/rune/src/compile/v1/mod.rs
  crates/rune/src/ir/eval/ir.rs
  crates/rune/src/ir/eval/ir_assign.rs
  crates/rune/src/ir/eval/ir_binary.rs
  crates/rune/src/ir/eval/ir_branches.rs
  crates/rune/src/ir/eval/ir_break.rs
  crates/rune/src/ir/eval/ir_call.rs
  crates/rune/src/ir/eval/ir_condition.rs
  crates/rune/src/ir/eval/ir_decl.rs
  crates/rune/src/ir/eval/ir_loop.rs
  crates/rune/src/ir/eval/ir_object.rs
  crates/rune/src/ir/eval/ir_scope.rs
  crates/rune/src/ir/eval/ir_set.rs
  crates/rune/src/ir/eval/ir_template.rs
  crates/rune/src/ir/eval/ir_tuple.rs
  crates/rune/src/ir/eval/ir_vec.rs
  crates/rune/src/ir/eval/mod.rs
  crates/rune/src/ir/ir_compiler.rs
  crates/rune/src/ir/ir_interpreter.rs
  crates/rune/src/macros/format_args.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/macros/quote_fn.rs
  crates/rune/src/macros/storage.rs
  crates/rune/src/macros/token_stream.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/worker/mod.rs
Labels: enhancement

#315 Clean up ir by removing underused traits and use of ConstValue
  crates/rune/src/compile/ir/eval/ir.rs
  crates/rune/src/compile/ir/eval/ir_assign.rs
  crates/rune/src/compile/ir/eval/ir_binary.rs
  crates/rune/src/compile/ir/eval/ir_branches.rs
  crates/rune/src/compile/ir/eval/ir_break.rs
  crates/rune/src/compile/ir/eval/ir_call.rs
  crates/rune/src/compile/ir/eval/ir_condition.rs
  crates/rune/src/compile/ir/eval/ir_decl.rs
  crates/rune/src/compile/ir/eval/ir_loop.rs
  crates/rune/src/compile/ir/eval/ir_object.rs
  crates/rune/src/compile/ir/eval/ir_scope.rs
  crates/rune/src/compile/ir/eval/ir_set.rs
  crates/rune/src/compile/ir/eval/ir_template.rs
  crates/rune/src/compile/ir/eval/ir_tuple.rs
  crates/rune/src/compile/ir/eval/ir_vec.rs
  crates/rune/src/compile/ir/eval/mod.rs
  crates/rune/src/compile/ir/eval/prelude.rs
  crates/rune/src/compile/ir/ir_compiler.rs
  crates/rune/src/compile/ir/ir_interpreter.rs
  crates/rune/src/compile/ir/ir_value.rs
  crates/rune/src/compile/ir/mod.rs
  crates/rune/src/compile/mod.rs
  crates/rune/src/macros/macro_context.rs
Labels: enhancement

#318 Clean up ir module more and narrow the use of IrCompile trait
  crates/rune/src/compile/ir/eval/ir.rs
  crates/rune/src/compile/ir/eval/ir_assign.rs
  crates/rune/src/compile/ir/eval/ir_binary.rs
  crates/rune/src/compile/ir/eval/ir_branches.rs
  crates/rune/src/compile/ir/eval/ir_call.rs
  crates/rune/src/compile/ir/eval/ir_condition.rs
  crates/rune/src/compile/ir/eval/ir_decl.rs
  crates/rune/src/compile/ir/eval/ir_loop.rs
  crates/rune/src/compile/ir/eval/ir_object.rs
  crates/rune/src/compile/ir/eval/ir_scope.rs
  crates/rune/src/compile/ir/eval/ir_set.rs
  crates/rune/src/compile/ir/eval/ir_template.rs
  crates/rune/src/compile/ir/eval/ir_tuple.rs
  crates/rune/src/compile/ir/eval/ir_vec.rs
  crates/rune/src/compile/ir/eval/mod.rs
  crates/rune/src/compile/ir/eval/prelude.rs
  crates/rune/src/compile/ir/ir_compiler.rs
  crates/rune/src/compile/ir/ir_eval.rs
  crates/rune/src/compile/ir/ir_value.rs
  crates/rune/src/compile/ir/mod.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/query/mod.rs
Labels: enhancement

#321 Remove Index and IndexLocal traits
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/index_local.rs
  crates/rune/src/indexing/locals.rs
  crates/rune/src/indexing/mod.rs
  crates/rune/src/worker/mod.rs
Labels: enhancement

#322 Introduce #[inststrument] macro
  crates/rune-macros/src/instrument.rs
  crates/rune-macros/src/lib.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/locals.rs
  crates/rune/src/query/mod.rs
Labels: enhancement

#323 Fix buggy self value
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/indexing/index.rs
  tests/tests/instance.rs
Labels: bug

#313 replace manual de/ser with derive
  crates/rune/Cargo.toml
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/const_value.rs
Labels: bug

#329 Native functions no longer requies Copy
  benches/benches/brainfuck.rs
  crates/rune/src/compile/module.rs
  crates/rune/src/compile/named.rs
  crates/rune/src/runtime/to_value.rs
  tests/Cargo.toml
  tests/src/capture_io.rs
  tests/src/capture_output.rs
  tests/src/lib.rs
Labels: enhancement, changelog

#331 Fix clippy lints
  crates/rune-cli/src/benches.rs
  crates/rune-modules/src/experiments/stringy_math_macro.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/src/build.rs
  crates/rune/src/compile/attrs.rs
  crates/rune/src/compile/ir/ir_compiler.rs
  crates/rune/src/compile/ir/ir_value.rs
  crates/rune/src/compile/mod.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/parse/mod.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/runtime/iterator.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/sources.rs
  crates/rune/src/worker/import.rs
Labels: enhancement

#333 Reduce the size of most tokens by inferring ast::Kind
  crates/rune/src/ast/attribute.rs
  crates/rune/src/ast/expr_binary.rs
  crates/rune/src/ast/expr_unary.rs
  crates/rune/src/ast/generated.rs
  crates/rune/src/ast/ident.rs
  crates/rune/src/ast/label.rs
  crates/rune/src/ast/lit_bool.rs
  crates/rune/src/ast/lit_byte.rs
  crates/rune/src/ast/lit_byte_str.rs
  crates/rune/src/ast/lit_char.rs
  crates/rune/src/ast/lit_number.rs
  crates/rune/src/ast/lit_str.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/macros/macro_context.rs
  tools/generate/src/main.rs
Labels: enhancement

#332 Fix binary precedence parser
  benches/benches/aoc_2020_11a.rs
  crates/rune/src/ast/expr.rs
  tests/tests/binary.rs
  tests/tests/test_range.rs
Labels: bug

#335 Hide more stuff and clean up some APIs
  crates/rune-macros/src/quote/inner.rs
  crates/rune-modules/src/core.rs
  crates/rune-modules/src/test.rs
  crates/rune/src/ast/expr.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/label.rs
  crates/rune/src/ast/lit.rs
  crates/rune/src/ast/lit_byte.rs
  crates/rune/src/ast/lit_byte_str.rs
  crates/rune/src/ast/lit_char.rs
  crates/rune/src/ast/lit_str.rs
  crates/rune/src/ast/macro_call.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/ast/span.rs
  crates/rune/src/ast/spanned_error.rs
  crates/rune/src/ast/token.rs
  crates/rune/src/diagnostics/emit.rs
  crates/rune/src/macros/format_args.rs
  crates/rune/src/macros/into_lit.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/macros/mod.rs
  crates/rune/src/macros/storage.rs
  crates/rune/src/parse/parser.rs
Labels: enhancement

#336 Rework how opaque identifiers are used
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/lib.rs
  crates/rune-macros/src/opaque.rs
  crates/rune-macros/src/option_spanned.rs
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr_call.rs
  crates/rune/src/ast/expr_closure.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_mod.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/macro_call.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/compile/ir/ir_interpreter.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/locals.rs
  crates/rune/src/parse/id.rs
  crates/rune/src/parse/mod.rs
  crates/rune/src/parse/opaque.rs
  crates/rune/src/query/mod.rs
  crates/rune/src/query/query_error.rs
  crates/rune/src/shared/gen.rs
  crates/rune/src/shared/items.rs
Labels: enhancement

#337 Remove underused public trait impls for Id
  crates/rune/src/id.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/locals.rs
  crates/rune/src/parse/id.rs
  crates/rune/src/query/mod.rs
Labels: enhancement

#339 Clean up tests
  tests/src/lib.rs
  tests/tests/vm_function.rs
  tests/tests/vm_test_external_fn_ptr.rs
Labels: enhancement

#343 Fix example in Module::option (fixes #236)
  crates/rune/src/compile/module.rs
Labels: bug, documentation

#347 Clean up Call and introduce ExecutionState
  crates/rune/src/runtime/call.rs
  crates/rune/src/runtime/generator.rs
  crates/rune/src/runtime/mod.rs
  crates/rune/src/runtime/stream.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_call.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/runtime/vm_execution.rs
Labels: enhancement

#349 Remove tailing item and unchecked casts
  crates/rune-cli/src/benches.rs
  crates/rune/src/compile/item.rs
  crates/rune/src/item.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/source_id.rs
Labels: enhancement

#350 Vm fields can be hidden
  crates/rune/src/runtime/function.rs
  crates/rune/src/runtime/protocol_caller.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement
