Repository rune-rs/rune, pull requests merged in 2021-01, with the labels that each got.

#241 add VecDeque + Vec::insert
  crates/runestick/src/modules/collections.rs
  crates/runestick/src/modules/vec.rs
  crates/runestick/src/vec.rs
Labels: enhancement, rust-likeness

#240 make float associated fns... associated.
  crates/runestick/src/modules/float.rs
Labels: bug, rust-likeness

#239 allow registration of native constants
  crates/runestick/src/context.rs
  crates/runestick/src/module.rs
Labels: enhancement, vm

#242 Fix typo in comment
  crates/rune-languageserver/src/state.rs
Labels: bug, documentation

#245 add lifetime to SourceLoader
  crates/rune/src/compiling/mod.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/load/mod.rs
  crates/rune/src/worker/mod.rs
Labels: bug, compiler

#248 Fix some intra-doc-links (and some others)
  crates/rune-languageserver/src/state.rs
  crates/rune-macros/src/lib.rs
  crates/rune-modules/src/lib.rs
  crates/rune/src/ast/lit.rs
  crates/rune/src/compiling/unit_builder.rs
  crates/rune/src/ir/mod.rs
  crates/rune/src/load/mod.rs
  crates/rune/src/query/mod.rs
  crates/runestick-macros/src/lib.rs
  crates/runestick/src/env.rs
  crates/runestick/src/iterator.rs
  crates/runestick/src/lib.rs
Labels: enhancement

#249 chore: Prepare 0.8.0 release
  CHANGELOG.md
  crates/rune-cli/Cargo.toml
  crates/rune-languageserver/Cargo.toml
  crates/rune-macros/Cargo.toml
  crates/rune-modules/Cargo.toml
  crates/rune-modules/src/core.rs
  crates/rune-modules/src/experiments/mod.rs
  crates/rune-modules/src/fmt.rs
  crates/rune-modules/src/fs.rs
  crates/rune-modules/src/http.rs
  crates/rune-modules/src/io.rs
  crates/rune-modules/src/json.rs
  crates/rune-modules/src/macros.rs
  crates/rune-modules/src/process.rs
  crates/rune-modules/src/rand.rs
  crates/rune-modules/src/signal.rs
  crates/rune-modules/src/test.rs
  crates/rune-modules/src/time.rs
  crates/rune-modules/src/toml.rs
  crates/rune-wasm/Cargo.toml
  crates/rune/Cargo.toml
  crates/runestick-macros/Cargo.toml
  crates/runestick/Cargo.toml
  editors/code/package-lock.json
  editors/code/package.json
Labels: chore
