Repository rune-rs/rune, pull requests merged in 2023-08, with the labels that each got.

#599 Allow underscores at the start of a variable
  crates/rune/src/ast/ident.rs
  crates/rune/src/parse/lexer.rs
  crates/rune/src/tests/vm_assign_exprs.rs
Labels: enhancement

#601 Use HRTBs for function traits
  .github/workflows/ci.yml
  book/src/safety.md
  crates/rune-cli/Cargo.toml
  crates/rune-cli/src/main.rs
  crates/rune-core/Cargo.toml
  crates/rune-core/README.md
  crates/rune-core/src/lib.rs
  crates/rune-languageserver/Cargo.toml
  crates/rune-languageserver/src/main.rs
  crates/rune-macros/Cargo.toml
  crates/rune-macros/src/any.rs
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/lib.rs
  crates/rune-modules/Cargo.toml
  crates/rune-modules/src/fs.rs
  crates/rune-modules/src/http.rs
  crates/rune-modules/src/lib.rs
  crates/rune-wasm/Cargo.toml
  crates/rune-wasm/src/http.rs
  crates/rune-wasm/src/lib.rs
  crates/rune/Cargo.toml
  crates/rune/src/hir/arena.rs
  crates/rune/src/hir/arena/tests.rs
  crates/rune/src/internal_macros.rs
  crates/rune/src/languageserver/state.rs
  crates/rune/src/lib.rs
  crates/rune/src/module/function_traits.rs
  crates/rune/src/module/function_traits/macros.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/stream.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime.rs
  crates/rune/src/runtime/access.rs
  crates/rune/src/runtime/any_obj.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/from_value.rs
  crates/rune/src/runtime/function.rs
  crates/rune/src/runtime/shared.rs
  crates/rune/src/runtime/static_string.rs
  crates/rune/src/runtime/stream.rs
  crates/rune/src/runtime/tests.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vm_execution.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/bug_344.rs
  crates/rune/src/tests/derive_from_to_value.rs
  crates/rune/src/tests/external_generic.rs
  crates/rune/src/tests/rename_type.rs
  examples/examples/rune_function_macro.rs
  tools/function_traits_permute.py
Labels: bug

#602 Fix doctests and add some for strings
  crates/rune-wasm/src/lib.rs
  crates/rune/src/cli/run.rs
  crates/rune/src/cli/tests.rs
  crates/rune/src/compile/unit_builder.rs
  crates/rune/src/doc/artifacts.rs
  crates/rune/src/doc/build/markdown.rs
  crates/rune/src/modules/char.rs
  crates/rune/src/modules/iter.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime/iterator.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_error.rs
Labels: enhancement

#603 More string tests
  crates/rune/src/compile/prelude.rs
  crates/rune/src/module.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/bytes.rs
  crates/rune/src/modules/future.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/modules/test.rs
  crates/rune/src/runtime/bytes.rs
Labels: enhancement

#604 Finish result documentation
  .github/workflows/ci.yml
  benches/benches/bench_main.rs
  crates/rune/src/cli.rs
  crates/rune/src/cli/loader.rs
  crates/rune/src/compile/context.rs
  crates/rune/src/compile/meta.rs
  crates/rune/src/doc/build.rs
  crates/rune/src/doc/build/type_.rs
  crates/rune/src/doc/context.rs
  crates/rune/src/doc/static/function.html.hbs
  crates/rune/src/doc/static/runedoc.css.hbs
  crates/rune/src/doc/static/type.html.hbs
  crates/rune/src/module.rs
  crates/rune/src/module/function_meta.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/core.rs
  crates/rune/src/modules/i64.rs
  crates/rune/src/modules/option.rs
  crates/rune/src/modules/result.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/modules/test.rs
  crates/rune/src/query/query.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/option.rs
  crates/rune/src/tests/result.rs
  crates/rune/src/tests/stmt_reordering.rs
  crates/rune/src/tests/tuple.rs
  crates/rune/src/tests/vm_general.rs
  examples/examples/proxy.rs
  scripts/book/primitives/primitives.rn
  site/content/posts/2020-12-07-faster-tests.md
  tools/builder/src/main.rs
Labels: enhancement

#605 Fix build
  crates/rune/src/module.rs
  crates/rune/src/module/module.rs
Labels: enhancement

#606 More numerical
  crates/rune/src/ast/lit_number.rs
  crates/rune/src/cli/tests.rs
  crates/rune/src/compile/context.rs
  crates/rune/src/modules.rs
  crates/rune/src/modules/f64.rs
  crates/rune/src/modules/i64.rs
  crates/rune/src/modules/num.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/parse/lexer.rs
Labels: enhancement

#607 Document std::collections::VecDeque
  crates/rune/src/modules/collections.rs
  crates/rune/src/modules/collections/vec_deque.rs
  crates/rune/src/modules/iter.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/object.rs
  crates/rune/src/runtime/protocol_caller.rs
  crates/rune/src/runtime/range.rs
  crates/rune/src/runtime/tuple.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/variant.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#608 Add more vec documentation
  crates/rune/src/cli/tests.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/from_value.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vec.rs
Labels: enhancement

#616 Make sure more protocols are implemented and documented
  crates/rune/src/modules/cmp.rs
  crates/rune/src/modules/f64.rs
  crates/rune/src/modules/i64.rs
  crates/rune/src/modules/object.rs
  crates/rune/src/modules/option.rs
  crates/rune/src/modules/tuple.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/object.rs
  crates/rune/src/runtime/shared.rs
  crates/rune/src/runtime/tuple.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/variant.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vec/iter.rs
Labels: enhancement

#619 Avoid calculating spans eagerly in Spanned derives
  crates/rune-macros/Cargo.toml
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/instrument.rs
  crates/rune-macros/src/lib.rs
  crates/rune-macros/src/option_spanned.rs
  crates/rune-macros/src/spanned.rs
  crates/rune/src/ast.rs
  crates/rune/src/ast/attribute.rs
  crates/rune/src/ast/block.rs
  crates/rune/src/ast/expr_match.rs
  crates/rune/src/ast/expr_select.rs
  crates/rune/src/ast/file.rs
  crates/rune/src/ast/generated.rs
  crates/rune/src/ast/grouped.rs
  crates/rune/src/ast/item_impl.rs
  crates/rune/src/ast/item_mod.rs
  crates/rune/src/ast/macro_utils.rs
  crates/rune/src/ast/spanned.rs
  tools/generate/src/main.rs
Labels: bug, changelog

#620 Rework Spanned implementation
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/internals.rs
  crates/rune-macros/src/spanned.rs
  crates/rune/src/ast/attribute.rs
  crates/rune/src/ast/expr_match.rs
  crates/rune/src/ast/expr_select.rs
  crates/rune/src/ast/fields.rs
  crates/rune/src/ast/item_const.rs
  crates/rune/src/ast/item_enum.rs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_mod.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/item_use.rs
  crates/rune/src/ast/macro_call.rs
  crates/rune/src/ast/macro_utils.rs
  crates/rune/src/ast/spanned.rs
  crates/rune/src/macros/token_stream.rs
Labels: enhancement

#621 More implementation and documentation
  crates/rune/src/lib.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/collections/hash_map.rs
  crates/rune/src/modules/collections/hash_set.rs
  crates/rune/src/modules/collections/vec_deque.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/tests/bug_326.rs
  crates/rune/src/tests/bug_344.rs
  examples/examples/custom_instance_fn.rs
Labels: enhancement

#622 Deprecate StaticString as a value
  crates/rune-modules/src/process.rs
  crates/rune/src/compile/ir/value.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/modules/core.rs
  crates/rune/src/modules/iter.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/const_value.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/from_value.rs
  crates/rune/src/runtime/key.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#624 Introduce rune::runtime::Formatter and more docs
  crates/rune-modules/src/http.rs
  crates/rune-modules/src/process.rs
  crates/rune/src/lib.rs
  crates/rune/src/modules/any.rs
  crates/rune/src/modules/cmp.rs
  crates/rune/src/modules/collections/hash_map.rs
  crates/rune/src/modules/collections/hash_set.rs
  crates/rune/src/modules/collections/vec_deque.rs
  crates/rune/src/modules/fmt.rs
  crates/rune/src/modules/io.rs
  crates/rune/src/modules/option.rs
  crates/rune/src/modules/result.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime.rs
  crates/rune/src/runtime/fmt.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_error.rs
Labels: enhancement

#625 A lot more documentation
  book/src/template_literals.md
  crates/rune-core/src/protocol.rs
  crates/rune-macros/src/any.rs
  crates/rune-macros/src/hash.rs
  crates/rune-macros/src/lib.rs
  crates/rune/src/compile/context.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/cmp.rs
  crates/rune/src/modules/generator.rs
  crates/rune/src/modules/ops.rs
  crates/rune/src/modules/test.rs
  crates/rune/src/runtime/generator.rs
  crates/rune/src/runtime/generator_state.rs
  crates/rune/src/runtime/range.rs
  crates/rune/src/runtime/range_from.rs
  crates/rune/src/runtime/range_full.rs
  crates/rune/src/runtime/range_inclusive.rs
  crates/rune/src/runtime/range_to.rs
  crates/rune/src/runtime/range_to_inclusive.rs
  crates/rune/src/runtime/static_type.rs
  crates/rune/src/tests/bug_344.rs
  crates/rune/src/tests/vm_generators.rs
  crates/rune/src/tests/vm_streams.rs
  scripts/generator_resume.rn
Labels: enhancement
