Repository rune-rs/rune, pull requests merged in 2023-06, with the labels that each got.

#539 fix and add tests for macrocall whitespace
  crates/rune/src/fmt.rs
  crates/rune/src/fmt/indent_writer.rs
  crates/rune/src/fmt/printer.rs
  crates/rune/src/fmt/tests.rs
Labels: bug

#528 Attribute Macros on Items
  crates/rune-macros/src/lib.rs
  crates/rune-macros/src/macro_.rs
  crates/rune-modules/src/experiments.rs
  crates/rune-modules/src/experiments/stringy_math_macro.rs
  crates/rune/src/ast.rs
  crates/rune/src/ast/attribute.rs
  crates/rune/src/ast/item.rs
  crates/rune/src/ast/macro_call.rs
  crates/rune/src/ast/macro_utils.rs
  crates/rune/src/compile/context.rs
  crates/rune/src/compile/meta.rs
  crates/rune/src/compile/meta_info.rs
  crates/rune/src/compile/unit_builder.rs
  crates/rune/src/fmt/printer.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/lib.rs
  crates/rune/src/macros.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/module.rs
  crates/rune/src/module/function_meta.rs
  crates/rune/src/module/module.rs
  crates/rune/src/modules/core.rs
  crates/rune/src/modules/fmt.rs
  crates/rune/src/modules/io.rs
  crates/rune/src/modules/macros.rs
  crates/rune/src/modules/test.rs
  crates/rune/src/runtime.rs
  crates/rune/src/runtime/runtime_context.rs
  crates/rune/src/testing.rs
  crates/rune/src/tests/custom_macros.rs
  examples/examples/concat_idents.rs
  examples/examples/parsing_in_macro.rs
Labels: enhancement

#543 Clean up local variable accesses
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/query.rs
  crates/rune/src/query/query.rs
Labels: enhancement

#550 Stop relying on layout of TypeId
  crates/rune/src/hash.rs
  crates/rune/src/modules/any.rs
Labels: bug, 0.12.x

#552 Simplify assemble
  crates/rune/src/build.rs
  crates/rune/src/compile.rs
  crates/rune/src/compile/compile_visitor.rs
  crates/rune/src/compile/error.rs
  crates/rune/src/compile/ir/compiler.rs
  crates/rune/src/compile/v1.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/scopes.rs
  crates/rune/src/hir.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/hir/scopes.rs
  crates/rune/src/languageserver/state.rs
  crates/rune/src/query/query.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/capture.rs
Labels: enhancement

#549 Allow seperate Serialization of a unit's instructions and debug info
  crates/rune/src/runtime/unit.rs
Labels: enhancement

#553 Don't attempt variable allocation during HIR lowering
  crates/rune/src/compile.rs
  crates/rune/src/compile/error.rs
  crates/rune/src/compile/ir.rs
  crates/rune/src/compile/ir/compiler.rs
  crates/rune/src/compile/ir/interpreter.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/scopes.rs
  crates/rune/src/hir.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/hir/scopes.rs
  crates/rune/src/query/query.rs
Labels: enhancement

#555 Don't clone attributes when parsing them
  crates/rune/src/ast/grouped.rs
  crates/rune/src/compile/attrs.rs
  crates/rune/src/compile/error.rs
  crates/rune/src/compile/meta.rs
  crates/rune/src/compile/v1.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/indexing.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/items.rs
  crates/rune/src/indexing/locals.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/query.rs
  crates/rune/src/query/query.rs
  crates/rune/src/shared.rs
  crates/rune/src/shared/items.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/attribute.rs
  crates/rune/src/tests/compiler_attributes.rs
  crates/rune/src/worker.rs
Labels: enhancement

#556 Only initialize item state once
  crates/rune/src/indexing.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/items.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/query/query.rs
  crates/rune/src/worker.rs
Labels: enhancement

#557 Lazily insert item identifiers
  crates/rune/src/indexing/index.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/macros/macro_context.rs
  crates/rune/src/worker.rs
Labels: enhancement

#558 More work in path lowering and field accesses
  crates/rune-core/src/hash.rs
  crates/rune-core/src/hash/into_hash.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/compile/ir.rs
  crates/rune/src/compile/ir/compiler.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/diagnostics.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/macros/macro_compiler.rs
  crates/rune/src/query.rs
  crates/rune/src/query/query.rs
  crates/rune/src/runtime/inst.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#562 Tuple and VecTuple incorrectly takes their values
  crates/rune/src/runtime/tuple.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vec_tuple.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/tuple.rs
Labels: bug

#564 Access ast elements in a qualified way
  crates/rune/src/fmt/printer.rs
Labels: enhancement

#565 Validate loop continue and break during HIR lowering
  crates/rune/src/ast.rs
  crates/rune/src/ast/expr_break.rs
  crates/rune/src/compile/compile.rs
  crates/rune/src/compile/ir.rs
  crates/rune/src/compile/ir/compiler.rs
  crates/rune/src/compile/ir/eval.rs
  crates/rune/src/compile/ir/interpreter.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/loops.rs
  crates/rune/src/fmt/printer.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/hir/scopes.rs
  crates/rune/src/indexing.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/tests/compiler_general.rs
  crates/rune/src/tests/continue_.rs
Labels: enhancement

#567 Sparser hir
  .github/workflows/ci.yml
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/loops.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering.rs
Labels: enhancement

#571 Make ::std tests optional
  .github/workflows/ci.yml
  crates/rune/src/cli/tests.rs
  crates/rune/src/lib.rs
Labels: enhancement

#573 Implement should_panic and improved test diagnostics
  crates/rune/src/cli/tests.rs
  crates/rune/src/doc.rs
  crates/rune/src/doc/artifacts.rs
  crates/rune/src/doc/build/markdown.rs
  crates/rune/src/modules/option.rs
  crates/rune/src/modules/result.rs
Labels: enhancement
