Repository rune-rs/rune, pull requests merged in 2024-10, with the labels that each got.

#832 rune: Fix freed address with diverging conditions
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/tests/bug_830.rn
  crates/rune/tests/diverging.rn
Labels: bug

#715 Convert Function::call (and related) to take GuardedArgs instead of Args
  crates/rune-macros/src/any.rs
  crates/rune/src/runtime/function.rs
  crates/rune/src/runtime/guarded_args.rs
  crates/rune/src/runtime/to_value.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/function_guardedargs.rs
Labels: enhancement

#833 rune: Move Future to use an internal vtable
  crates/rune/src/runtime/future.rs
  crates/rune/src/runtime/tests.rs
Labels: enhancement

#837 rune_alloc: More nightly things being stabilized
  crates/rune-alloc/src/lib.rs
  crates/rune-alloc/src/ptr.rs
Labels: enhancement

#840 rune: Rework context spans
  crates/rune/src/compile/compile.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/diagnostics/mod.rs
Labels: enhancement

#841 rune: Make miri happy about how environments are passed
  crates/rune/src/runtime/env.rs
  crates/rune/src/runtime/vm.rs
Labels: bug

#843 rune: Move ranges away from being built-in types
  crates/rune-macros/src/any.rs
  crates/rune-macros/src/context.rs
  crates/rune/src/modules/ops.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime/any_obj.rs
  crates/rune/src/runtime/mod.rs
  crates/rune/src/runtime/range.rs
  crates/rune/src/runtime/range_from.rs
  crates/rune/src/runtime/range_full.rs
  crates/rune/src/runtime/range_inclusive.rs
  crates/rune/src/runtime/range_to.rs
  crates/rune/src/runtime/range_to_inclusive.rs
  crates/rune/src/runtime/tests.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_error.rs
Labels: enhancement

#845 all: Bump dependencies
  crates/rune-core/Cargo.toml
  crates/rune-modules/Cargo.toml
  crates/rune-wasm/Cargo.toml
  crates/rune/Cargo.toml
  crates/rune/src/doc/markdown.rs
  crates/rune/src/languageserver/mod.rs
  crates/rune/src/runtime/unit/byte_code.rs
  examples/Cargo.toml
  tools/builder/Cargo.toml
  tools/builder/src/main.rs
  tools/site/Cargo.toml
Labels: enhancement

#846 rune: Fix build
  crates/rune/src/runtime/unit/byte_code.rs
Labels: chore

#849 rune: Mark consume as #[inline(always)]
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#847 rune::doc: Fix rendering of conflicting hashes
  crates/rune/src/doc/build.rs
  crates/rune/src/modules/f64.rs
  crates/rune/src/modules/i64.rs
Labels: bug

#848 rune: Store String in AnyObj instead of Mutable (relates #844)
  crates/rune-modules/src/base64.rs
  crates/rune-modules/src/http.rs
  crates/rune-modules/src/json.rs
  crates/rune-modules/src/process.rs
  crates/rune-modules/src/toml.rs
  crates/rune/src/any.rs
  crates/rune/src/compile/error.rs
  crates/rune/src/compile/ir/eval.rs
  crates/rune/src/exported_macros.rs
  crates/rune/src/macros/format_args.rs
  crates/rune/src/modules/any.rs
  crates/rune/src/modules/cmp.rs
  crates/rune/src/modules/collections/hash_map.rs
  crates/rune/src/modules/collections/hash_set.rs
  crates/rune/src/modules/collections/vec_deque.rs
  crates/rune/src/modules/f64.rs
  crates/rune/src/modules/fmt.rs
  crates/rune/src/modules/i64.rs
  crates/rune/src/modules/io.rs
  crates/rune/src/modules/iter.rs
  crates/rune/src/modules/mem.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime/access.rs
  crates/rune/src/runtime/any_obj.rs
  crates/rune/src/runtime/args.rs
  crates/rune/src/runtime/const_value.rs
  crates/rune/src/runtime/control_flow.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/from_value.rs
  crates/rune/src/runtime/mod.rs
  crates/rune/src/runtime/panic.rs
  crates/rune/src/runtime/stack.rs
  crates/rune/src/runtime/tuple.rs
  crates/rune/src/runtime/type_info.rs
  crates/rune/src/runtime/unit/storage.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/macros.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/tests/string_debug.rs
Labels: enhancement

#850 all: remove inconsistent ::core use
  crates/rune-alloc/src/boxed.rs
  crates/rune-alloc/src/clone.rs
  crates/rune-core/src/protocol.rs
  crates/rune/src/compile/error.rs
  crates/rune/src/compile/mod.rs
  crates/rune/src/runtime/macros.rs
  crates/rune/src/support.rs
Labels: chore

#853 ci: Update build to run more things in parallel
  .github/workflows/ci.yml
Labels: enhancement

#851 rune: Store Bytes in AnyObj instead of Mutable (relates #844)
  crates/rune/src/compile/context.rs
  crates/rune/src/modules/bytes.rs
  crates/rune/src/modules/collections/mod.rs
  crates/rune/src/runtime/borrow_mut.rs
  crates/rune/src/runtime/borrow_ref.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/const_value.rs
  crates/rune/src/runtime/tests.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#854 rune: Clean up more internal nits
  crates/rune/src/cli/tests.rs
  crates/rune/src/compile/ir/eval.rs
  crates/rune/src/compile/ir/interpreter.rs
  crates/rune/src/modules/future.rs
  crates/rune/src/modules/iter.rs
  crates/rune/src/modules/string.rs
  crates/rune/src/runtime/borrow_mut.rs
  crates/rune/src/runtime/borrow_ref.rs
  crates/rune/src/runtime/const_value.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/function.rs
  crates/rune/src/runtime/mod.rs
  crates/rune/src/runtime/range.rs
  crates/rune/src/runtime/range_from.rs
  crates/rune/src/runtime/range_inclusive.rs
  crates/rune/src/runtime/tests.rs
  crates/rune/src/runtime/tuple.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/macros.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/vm_function.rs
Labels: chore

#857 rune::cli: Unify coloring and improve test naming
  crates/rune-core/src/protocol.rs
  crates/rune/src/cli/mod.rs
  crates/rune/src/cli/out.rs
  crates/rune/src/cli/tests.rs
  crates/rune/src/doc/artifacts.rs
  crates/rune/src/doc/build.rs
  crates/rune/src/doc/build/type_.rs
  crates/rune/src/doc/mod.rs
Labels: enhancement

#859 rune: Clone during Vec::resize (fixes #858)
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vec.rs
Labels: bug

#819 modules: Expand http module with put, delete, head, auth and more
  crates/rune-modules/src/http.rs
Labels: enhancement

#815 modules: Expand time module with Duration, Interval and Instant support
  crates/rune-modules/src/time.rs
Labels: enhancement

#862 macros: Clean up Context use and ensure we don't miss errors
  crates/rune-macros/src/any.rs
  crates/rune-macros/src/const_value.rs
  crates/rune-macros/src/context.rs
  crates/rune-macros/src/from_value.rs
  crates/rune-macros/src/lib.rs
  crates/rune-macros/src/opaque.rs
  crates/rune-macros/src/parse.rs
  crates/rune-macros/src/spanned.rs
  crates/rune-macros/src/to_tokens.rs
  crates/rune-macros/src/to_value.rs
Labels: enhancement

#863 rune: Store GeneratorState in AnyObj instead of Mutable (relates #844)
  crates/rune/src/module/module.rs
  crates/rune/src/modules/ops/generator.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/generator_state.rs
  crates/rune/src/runtime/inst.rs
  crates/rune/src/runtime/type_info.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#864 rune: Make formatter reference a local value
  crates/rune/src/modules/option.rs
  crates/rune/src/modules/result.rs
  crates/rune/src/runtime/fmt.rs
  crates/rune/src/runtime/format.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement

#865 rune: Store Vec in AnyObj instead of Mutable (relates #844)
  crates/rune/src/compile/ir/interpreter.rs
  crates/rune/src/modules/future.rs
  crates/rune/src/modules/vec.rs
  crates/rune/src/runtime/const_value.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/serde.rs
  crates/rune/src/runtime/vec.rs
  crates/rune/src/runtime/vec_tuple.rs
  crates/rune/src/runtime/vm.rs
Labels: enhancement
