Repository rune-rs/rune, pull requests merged in 2024-04, with the labels that each got.

#686 Improve Any derive documentation
  crates/rune/src/any.rs
  crates/rune/src/lib.rs
Labels: enhancement

#688 Add support for captured arguments from macros
  book/src/hot_reloading.md
  book/src/multithreading.md
  crates/rune/src/compile/context.rs
  crates/rune/src/lib.rs
  crates/rune/src/macros/format_args.rs
  crates/rune/src/macros/token_stream.rs
  crates/rune/src/modules.rs
  crates/rune/src/modules/io.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/builtin_macros.rs
Labels: enhancement, rust-likeness

#689 Rename delay_for to sleep
  book/src/loops.md
  crates/rune-wasm/src/time.rs
  examples/examples/tokio_spawn.rs
  site/content/_index.md
Labels: bug, documentation

#691 Added bytes support for http
  crates/rune-modules/src/http.rs
Labels: enhancement

#695 Use explicit macos versions
  .github/workflows/release.yml
Labels: enhancement

#694 Add Iterator::filter_map
  crates/rune/src/modules/iter.rs
  crates/rune/src/runtime/iterator.rs
Labels: enhancement

#697 Support constants in patterns (fixes #696)
  crates/rune/src/hir/lowering.rs
  crates/rune/src/tests/patterns.rs
Labels: bug

#699 Set version to 0.14.0 and bump Musli
  crates/rune-alloc-macros/Cargo.toml
  crates/rune-alloc/Cargo.toml
  crates/rune-cli/Cargo.toml
  crates/rune-core/Cargo.toml
  crates/rune-languageserver/Cargo.toml
  crates/rune-macros/Cargo.toml
  crates/rune-modules/Cargo.toml
  crates/rune-modules/src/experiments.rs
  crates/rune-modules/src/fs.rs
  crates/rune-modules/src/http.rs
  crates/rune-modules/src/json.rs
  crates/rune-modules/src/process.rs
  crates/rune-modules/src/rand.rs
  crates/rune-modules/src/signal.rs
  crates/rune-modules/src/time.rs
  crates/rune-modules/src/toml.rs
  crates/rune-wasm/Cargo.toml
  crates/rune/Cargo.toml
  no-std/Cargo.toml
  no-std/examples/minimal.rs
Labels: chore

#701 Add more public VmResult errors
  crates/rune/src/runtime/vm_error.rs
Labels: enhancement

#702 Closure environments
  crates/rune/src/compile/compile.rs
  crates/rune/src/compile/unit_builder.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/runtime/args.rs
  crates/rune/src/runtime/function.rs
  crates/rune/src/runtime/inst.rs
  crates/rune/src/runtime/protocol_caller.rs
  crates/rune/src/runtime/unit.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/bug_700.rs
Labels: bug
