Repository rune-rs/rune, pull requests merged in 2024-08, with the labels that each got.

#792 chore: Unfudge release build
  .github/workflows/ci.yml
  crates/rune/src/compile/v1/needs.rs
  crates/rune/src/shared/mod.rs
Labels: enhancement

#793 chore: Add missing feature flag
  .github/workflows/ci.yml
  crates/rune/src/compile/context.rs
  crates/rune/src/compile/docs.rs
  crates/rune/src/compile/meta.rs
  crates/rune/src/doc/mod.rs
  crates/rune/src/doc/visitor.rs
  crates/rune/src/runtime/unit/storage.rs
Labels: bug

#723 modules: add base64 module
  crates/rune-macros/src/function.rs
  crates/rune-modules/Cargo.toml
  crates/rune-modules/src/base64.rs
  crates/rune-modules/src/lib.rs
Labels: enhancement

#714 Support autocomplete for Ace editor
  crates/rune/src/cli/ace.rs
  crates/rune/src/cli/mod.rs
  crates/rune/src/compile/prelude.rs
  crates/rune/src/doc/autocomplete.rs
  crates/rune/src/doc/build.rs
  crates/rune/src/doc/build/markdown.rs
  crates/rune/src/doc/mod.rs
  examples/README.md
  examples/ace/.gitignore
  examples/ace/README.md
  examples/ace/index.html
Labels: enhancement

#794 ace: built rune-mode and change how autocompleter is configured
  .github/workflows/ci.yml
  crates/rune/src/ace/autocomplete.rs
  crates/rune/src/ace/mod.rs
  crates/rune/src/ace/static/rune-completer.js
  crates/rune/src/ace/static/rune-highlight-rules.js
  crates/rune/src/ace/static/rune-mode.js
  crates/rune/src/cli/ace.rs
  crates/rune/src/compile/context.rs
  crates/rune/src/doc/build.rs
  crates/rune/src/doc/markdown.rs
  crates/rune/src/doc/mod.rs
  crates/rune/src/lib.rs
  examples/ace/.gitignore
  examples/ace/index.html
Labels: enhancement

#795 languageserver: add support for utf-8 and format selection
  crates/rune/src/compile/mod.rs
  crates/rune/src/compile/options.rs
  crates/rune/src/fmt/format.rs
  crates/rune/src/fmt/mod.rs
  crates/rune/src/fmt/output.rs
  crates/rune/src/fmt/tests/macros.rs
  crates/rune/src/fmt/tests/mod.rs
  crates/rune/src/indexing/indexer.rs
  crates/rune/src/languageserver/mod.rs
  crates/rune/src/languageserver/state.rs
  crates/rune/src/source.rs
Labels: enhancement, languageserver

#796 grammar: fix 'is not' parsing
  crates/rune/src/grammar/parser.rs
Labels: bug

#797 rune: move more tests to rune
  crates/rune/src/compile/mod.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/char.rs
  crates/rune/src/tests/float.rs
  crates/rune/src/tests/for_loop.rs
  crates/rune/src/tests/instance.rs
  crates/rune/src/tests/int.rs
  crates/rune/src/tests/iter.rs
  crates/rune/src/tests/loops.rs
  crates/rune/src/tests/result.rs
  crates/rune/src/tests/stmt_reordering.rs
  crates/rune/src/tests/vm_closures.rs
  crates/rune/src/tests/vm_generators.rs
  crates/rune/src/tests/vm_is.rs
  crates/rune/src/tests/vm_lazy_and_or.rs
  crates/rune/src/tests/vm_option.rs
  crates/rune/src/tests/vm_pat.rs
  crates/rune/src/tests/vm_streams.rs
  crates/rune/src/tests/vm_try.rs
  crates/rune/src/tests/vm_tuples.rs
  crates/rune/src/tests/vm_typed_tuple.rs
  crates/rune/src/tests/vm_types.rs
  crates/rune/tests/char.rn
  crates/rune/tests/closures.rn
  crates/rune/tests/float.rn
  crates/rune/tests/generators.rn
  crates/rune/tests/instance.rn
  crates/rune/tests/int_ops.rn
  crates/rune/tests/iter.rn
  crates/rune/tests/lazy_and_or.rn
  crates/rune/tests/loops.rn
  crates/rune/tests/operator_is.rn
  crates/rune/tests/option.rn
  crates/rune/tests/pat.rn
  crates/rune/tests/reordering.rn
  crates/rune/tests/result.rn
  crates/rune/tests/streams.rn
  crates/rune/tests/try.rn
  crates/rune/tests/tuples.rn
  crates/rune/tests/typed_tuple.rn
  scripts/generator_resume.rn
Labels: enhancement

#798 tracing: add tracing feature to shim out tracing
  crates/rune-macros/src/lib.rs
  crates/rune-modules/README.md
  crates/rune-tracing-macros/Cargo.toml
  crates/rune-tracing-macros/README.md
  crates/rune-tracing-macros/src/instrument.rs
  crates/rune-tracing-macros/src/lib.rs
  crates/rune-tracing/Cargo.toml
  crates/rune-tracing/README.md
  crates/rune-tracing/src/lib.rs
  crates/rune/Cargo.toml
  crates/rune/src/cli/loader.rs
  crates/rune/src/compile/ir/compiler.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/needs.rs
  crates/rune/src/doc/build.rs
  crates/rune/src/doc/context.rs
  crates/rune/src/grammar/grammar.rs
  crates/rune/src/grammar/parser.rs
  crates/rune/src/hir/lowering.rs
  crates/rune/src/hir/scopes.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/indexing/scopes.rs
  crates/rune/src/languageserver/state.rs
  crates/rune/src/runtime/stack.rs
  crates/rune/src/runtime/vm.rs
  crates/rune/src/shared/mod.rs
Labels: enhancement

#799 fmt: fix item_fn
  crates/rune/src/compile/mod.rs
  crates/rune/src/fmt/format.rs
Labels: enhancement

#806 index: more cleanups
  crates/rune/src/indexing/index.rs
Labels: enhancement

#807 Update lexing and parsing
  assets/tokens.yaml
  crates/rune/Cargo.toml
  crates/rune/src/ast/generated.rs
  crates/rune/src/compile/options.rs
  crates/rune/src/fmt/format.rs
  crates/rune/src/grammar/grammar.rs
  crates/rune/src/grammar/parser.rs
  crates/rune/src/tests.rs
Labels: enhancement

#808 fmt: mark out items in grammar
  assets/tokens.yaml
  crates/rune/src/ast/generated.rs
  crates/rune/src/fmt/format.rs
  crates/rune/src/grammar/grammar.rs
  crates/rune/src/grammar/tree.rs
Labels: enhancement

#809 grammar: use inner expressions as appropriate
  crates/rune/src/compile/error.rs
  crates/rune/src/fmt/format.rs
  crates/rune/src/fmt/tests/mod.rs
  crates/rune/src/grammar/grammar.rs
Labels: enhancement

#813 Support non-ASCII identifiers
  crates/rune/Cargo.toml
  crates/rune/src/parse/lexer.rs
  crates/rune/tests/non_ascii_idents.rn
Labels: enhancement, rust-likeness
