Repository rune-rs/rune, pull requests merged in 2024-12, with the labels that each got.

#895 Fix Clippy lints
  crates/rune-alloc/src/btree/map.rs
  crates/rune-alloc/src/btree/map/entry.rs
  crates/rune-alloc/src/btree/node.rs
  crates/rune-alloc/src/btree/set.rs
  crates/rune-alloc/src/hashbrown/map.rs
  crates/rune-alloc/src/hashbrown/raw/bitmask.rs
  crates/rune-alloc/src/hashbrown/serde.rs
  crates/rune-alloc/src/hashbrown/set.rs
  crates/rune-alloc/src/serde/de.rs
  crates/rune-alloc/src/slice.rs
  crates/rune-alloc/src/string/mod.rs
  crates/rune-alloc/src/string/serde.rs
  crates/rune-alloc/src/vec/drain.rs
  crates/rune-alloc/src/vec/mod.rs
  crates/rune-alloc/src/vec_deque/drain.rs
  crates/rune-alloc/src/vec_deque/into_iter.rs
  crates/rune-alloc/src/vec_deque/mod.rs
  crates/rune-core/src/item/iter.rs
  crates/rune/src/ast/path.rs
  crates/rune/src/build.rs
  crates/rune/src/compile/attrs.rs
  crates/rune/src/compile/v1/assemble.rs
  crates/rune/src/compile/v1/linear.rs
  crates/rune/src/compile/v1/scopes.rs
  crates/rune/src/doc/markdown.rs
  crates/rune/src/grammar/parser.rs
  crates/rune/src/grammar/tree.rs
  crates/rune/src/hir/arena.rs
  crates/rune/src/hir/hir.rs
  crates/rune/src/hir/lowering2.rs
  crates/rune/src/indexing/indexer.rs
  crates/rune/src/languageserver/envelope.rs
  crates/rune/src/languageserver/state.rs
  crates/rune/src/macros/quote_fn.rs
  crates/rune/src/modules/fmt.rs
  crates/rune/src/parse/parser.rs
  crates/rune/src/query/query.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/unit/byte_code.rs
  crates/rune/src/runtime/value.rs
  crates/rune/src/runtime/value/rtti.rs
  crates/rune/src/runtime/vm_error.rs
  crates/rune/src/workspace/glob.rs
  crates/rune/src/workspace/spanned_value.rs
  examples/examples/hot_reloading/path_reloader.rs
Labels: chore

#898 Remove #[start] entrypoints (closes #897)
  crates/rune/src/runtime/from_value.rs
  no-std/Cargo.toml
  no-std/examples/minimal.rs
Labels: enhancement

#896 Update `resolve.rs` reference
  book/src/compiler_guide.md
Labels: documentation
