Repository rune-rs/rune, pull requests merged in 2025-01, with the labels that each got.

#899 Add some functions for Bytes
  crates/rune/src/modules/bytes.rs
  crates/rune/src/runtime/bytes.rs
  crates/rune/src/runtime/mod.rs
  scripts/bytes.rn
Labels: enhancement

#902 Fix more lints
  crates/rune-alloc-macros/src/try_clone.rs
  crates/rune-alloc/src/btree/navigate.rs
  crates/rune-alloc/src/hashbrown/map.rs
  crates/rune-tracing-macros/src/instrument.rs
  crates/rune-tracing-macros/src/lib.rs
Labels: chore

#903 Fix missing interface error in rune-wasm
  crates/rune-wasm/src/lib.rs
  crates/rune/src/runtime/value.rs
Labels: bug

#904 Add optional static typing to functions and structs
  crates/rune/src/ast/item_fn.rs
  crates/rune/src/ast/item_struct.rs
  crates/rune/src/ast/mod.rs
  crates/rune/src/ast/rn_type.rs
  crates/rune/src/indexing/index.rs
  crates/rune/src/tests.rs
  crates/rune/src/tests/static_typing.rs
Labels: enhancement
